### ISSUE TITLE
Create Version Check Alert

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#1]
App should call version check api
if new version exists and is required
don't allow progress until app is updated
- [x] @kidbombay create version check api

**Comment by kidbombay** [comment]
```
{
"ios_app_version": 1.4,
"ios_app_link": "http://bit.ly/UpAllNight_AppStore",
"push_notification_keys": [
"user.follow",
"user.facebook_friend_joins",
"event.create",
"event.reminder"
],
"apps": {
"upallnight_ios": {
"app_version": 1.4,
"app_link": "http://bit.ly/UpAllNight_AppStore"
},
"bouncer_ios": {
"app_version": 1,
"app_link": "http://upallnight.us"
}
}
}
```
from http://upallnight.us/versions.json

**Comment by kidbombay** [comment]
@mayur43s use the apps field for bouncer.

**Comment by kidbombay** [comment]
@mayur43s this how this should work
- [ ] Any time app launches/reopens call the version check api
- [ ] If apps.bouncer_ios.app_version is greater than your local version string "1.0.0" show an alert with the following message
"Please update your app to the latest version." that links to apps.bouncer_ios.app_link

**Comment by qualityanalystweb** [comment]
@mayur43s  Unable to test it. Please push a dummy update and let me know.

**Comment by kidbombay** [comment]
Sasi I can update the backend to force the check to show. I'll QA this.

**Comment by qualityanalystweb** [comment]
Pressing against the "Update" button redirects to web app opened up in Safari browser in iPod touch iOS 10.2.1
![force update app](https://cloud.githubusercontent.com/assets/16776424/23546550/b23e0f0c-ffc5-11e6-9af0-efb4eb80455d.jpg)

**Comment by kidbombay** [comment]
Yes that's right. We haven't set the link to update yet since the app isn't released.

**Comment by kidbombay** [comment]
I've set the version to be 0.7.5 on server. Not seeing the version update alert now.

**Comment by kidbombay** [comment]
NVM server wasn't updated yet.
