### ISSUE TITLE
2 Line TitleView

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#12]
We need an estimate on how much work it would be to create a reusable 2 line title view. It would be used in navigation bars as the title view.

It should respond to auto layout correctly and size itself on all devices.
It should support the first line having one font style
it should support the second line have another font style

Both lines should ellipse text if too long
TitleView should still work if left or right nav items are added.

**Comment by kidbombay** [comment]
https://www.dropbox.com/s/jqst0bf9rvvf53n/order_new_01.png?dl=0

**Comment by kidbombay** [comment]
https://www.dropbox.com/s/oqz6wtwyze0qm1p/ticket_detail_gold_08.png?dl=0

**Comment by BenCordial** [comment]
Can't we just copy over that component from the other app?

**Comment by kidbombay** [comment]
I think that's an Objective C component?
