### ISSUE TITLE
Create Scan Screen

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#3]

**Comment by BenCordial** [comment]
Code is done... just needs the network endpoint to be done.

**Comment by kidbombay** [comment]
What model you expecting back other than for error states?

Ketan Anjaria

Designer <http://kidbombay.com>, Writer <https://medium.com/@kidbombay>,
Photographer <http://instagram.com/kidbombay>

@kidbombay <http://twitter.com/kidbombay>

415-260-8742

**Comment by BenCordial** [comment]
We discussed having the following outcomes from submitting a scanned slug:

* OK: Returns the name of the ticket holder and the ticket name.
* ALREADY CHECKED IN: Returns the name of the ticket holder, name of the ticket and the checkin time.
* WRONG EVENT: Returns the name and time of the event the ticket is for to display.
* UNKNOWN TICKET: The ticket is completely unknown to the Up All Night system.

**Comment by kidbombay** [comment]
http://staging.upallnight.us/docs/events/scan_a_ticket
http://staging.upallnight.us/docs/events/scan_a_ticket_error:_already_checked_in
http://staging.upallnight.us/docs/events/scan_a_ticket_error:_invalid_slug

api updated on staging
