### ISSUE TITLE
Events in LIVE tab should be listed in chronological order

### ISSUE THREAD

**Issue by robgrega** [flavorgroup/bouncer#36]
As a user, I would expect to see events being listed in the order that they happen next.
The first event in the future should be listed first.
Then the event after that, etc...

Currently they seem to be in the order in which the user was added to the respective team lists.

![img_2510](https://cloud.githubusercontent.com/assets/10214799/22955400/b902fdfe-f2d0-11e6-93aa-ebbdeaf56e88.PNG)

**Comment by kidbombay** [comment]
Oldest first?

**Comment by robgrega** [comment]
We're looking at events in the future. 
So the next event to happen should come first.
Then the event after that, etc...

**Comment by kidbombay** [comment]
@mayur43s this is good you fixed this but I need to fix on backend
https://upallnight.us/my_events is correct right @robgrega ?

**Comment by robgrega** [comment]
The events are in the correct order on the LIVE tab on the web
but they are not in the correct order on the PAST tab on the web.

I'll add a screenshot to the other issue.
