### ISSUE TITLE
Events in PAST tab should be listed in reverse chronological order

### ISSUE THREAD

**Issue by robgrega** [flavorgroup/bouncer#37]
As a user, if I'm looking at events in the past
I would expect the most recent past event to be first on the list
Then the second most recent, etc...

These events seem to have no order.
But I believe that like the LIVE tab, they are being shown in the order that the user was added to the team.

![img_2511](https://cloud.githubusercontent.com/assets/10214799/22955505/50cf0c86-f2d1-11e6-9732-23e62c1eed57.PNG)

**Comment by kidbombay** [comment]
Mayur it's good that you fixed this but it should be fixed on back end due to paging.
https://upallnight.us/my_events/past @robgrega this is correct right?

**Comment by robgrega** [comment]
Not correct on the web @kidbombay 

![myevents_badorder](https://cloud.githubusercontent.com/assets/10214799/23086037/c9a4038c-f51f-11e6-8e33-7faa9718043b.png)
