### ISSUE TITLE
Get a flashlight icon for off/on state

### ISSUE THREAD

**Issue by mayur43s** [flavorgroup/bouncer#42]
- [x] We need to have an flashlight icon for off/on state on scan screen.

**Comment by kidbombay** [comment]
On
https://www.dropbox.com/s/7xihsceo8clmvhe/scan_light_on_01.png?dl=0

Off
https://www.dropbox.com/s/sr860r85y3549ht/scan_02.png?dl=0

Icon in sketch file

**Comment by kidbombay** [comment]
Sketch file is now - https://www.dropbox.com/s/v9s0giykxv0u95y/bouncer.sketch?dl=0

**Comment by mayur43s** [comment]
I've done the changes for updating the UI of scan screen to show new outline and flashlight icon and  the changes are there in Bouncer 0.7.2 (1).

**Comment by mayur43s** [comment]
I've also done the changes for version checking for not prompting the user to update the app if the installed version is higher than the version returned from the API. 
It also contains the changes for hiding the status bar on the app launch screen.

**Comment by kidbombay** [comment]
Looks great!
