### ISSUE TITLE
Submit Bouncer to Apple for Approval

### ISSUE THREAD

**Issue by robgrega** [flavorgroup/bouncer#46]
Rob to do:

Deliver link to screenshots folder

cc @kidbombay @mayur43s

**Comment by kidbombay** [comment]
Use these screens in this order
https://www.dropbox.com/s/ci1m0w1orqruecg/my_events_live_appstore.png?dl=0
https://www.dropbox.com/s/ina24m9qxjtjnbs/scan_confirmed_appstore.png?dl=0
https://www.dropbox.com/s/sxrzwmay6l3yhma/tickets_appstore.png?dl=0

**Comment by robgrega** [comment]
**Description:** @PremKumta @kidbombay please approve

Bouncer lets you manage your Up All Night events on your iPhone, iPad or iPod Touch. Monitor your ticket sales in real-time, check-in your guests, and track attendance, live.

It’s super fast and super easy to use.

	▪	Scan ticket QR codes.
	▪	Instant search to find and check in any attendee with a quickness.
	▪	Multiple devices are always in sync.

Simply sign in and get instant access to all of your event dashboards on upallnight.us

--

**Smaller B Icon:**

https://www.dropbox.com/sh/fizao3lmt89yxhd/AABlWq294ScaEQtj99ECNWI3a?dl=0

**App Store Screenshots**

https://www.dropbox.com/sh/uiixrsxqch7covm/AACk7zv1Jf6YomzLFNVxfsTya?dl=0

**Comment by PremKumta** [comment]
@mayur43s This is good to submit to apple with the description above and all screenshots per Rob's edited post above.

**Comment by PremKumta** [comment]
keywords: Events, Up All Night, Tickets, Check In, QR Code, Dance
copyright: Potrero Hill Hoodlums

contact - Prem@upallnight.us

**Comment by mayur43s** [comment]
I've submitted the app to Apple and it's in review now. I've also enabled manual release so even after app approval we will have the control to release it to App Store.

**Bouncer 0.7.0**
