### ISSUE TITLE
Not every page loading when scrolling

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#49]
https://upallnight.us/events/bouncer-test-2/guestlists

Go to ticket list in bouncer for this event
26 names should appear
but only 25 do

cc: @ryandavis6

**Comment by kidbombay** [comment]
https://upallnight.us/events/ketan-s-lots-of-tickets-test-event/guestlists
200 tickets
Not all loading

**Comment by kidbombay** [comment]
This is working but when you load the next page the scrolling stops abruptly. We shouldn't have that.
It should be smooth.

**Comment by kidbombay** [comment]
test on latest build

**Comment by kidbombay** [comment]
Something is still happening with the loading not being smooth. You go to next page and it stops scrolling immediately.

**Comment by qualityanalystweb** [comment]
@kidbombay When scrolled down to next page or 2-3 pages speedy then there is a bump in scrolling when again scrolled it loads within a second but there is a noticeable lag. I think this can be ignored since next press up scrolling within a second it loads the next tickets...

**Comment by kidbombay** [comment]
There should be no lag.

**Comment by mayur43s** [comment]
I've done the changes for loading the table in main thread so we can check the scrolling in latest build 0.7.0 (1).

**Comment by kidbombay** [comment]
Hmm I'm not seeing this. It still seems to jerk or pause when loading more events.
Have you test with this event?
User unable to download his own resume #43

**Comment by PremKumta** [comment]
i'm still seeing the lag while scrolling but don't think this should stop us from submitting

**Comment by PremKumta** [comment]
still seeing the lag specifically - Ketan's Lots of Tickets Test Event
