### ISSUE TITLE
Create Tickets Controller

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#5]
API
http://staging.upallnight.us/docs/guestlist_contacts/get_all_guest_list_contacts_for_event

- [x] paging list of guestlist contacts
- [x] allow search as you type
- [x] swiping left checks guest list contact in (display green bar)
- [x] swiping right unchecks guest list contact in

**Comment by kidbombay** [comment]
This is on production as well

**Comment by kidbombay** [comment]
http://staging.upallnight.us/docs/guestlist_contacts/search_for_guest_list_contacts_by_name
search for guestlist contacts by name

**Comment by kidbombay** [comment]
Check in /check out
http://staging.upallnight.us/docs/guestlist_contacts/checkin_guest_list_contact
http://staging.upallnight.us/docs/guestlist_contacts/checkout_guest_list_contact_

**Comment by BenCordial** [comment]
Done
