### ISSUE TITLE
Ticket screen goes blank

### ISSUE THREAD

**Issue by mayur43s** [flavorgroup/bouncer#51]
Step 1: On tickets screen search for contact.
Step 2: Hide keyboard by pressing search on keyboard.
Step 3: Switch tab.
Step 4: Again come on tickets tab.
Step 5: Cancel the search by pressing cancel button on searchbar.

It will make whole screen blank and searchbar also disappear.

In order to see searchbar and contacts user needs to switch to different tab and come again on tickets tab.

**Comment by mayur43s** [comment]
![img_3810](https://cloud.githubusercontent.com/assets/5563481/23274538/1ae7b4f6-fa29-11e6-9295-596c24a482bf.JPG)

**Comment by kidbombay** [comment]
Can you just not make it a done button on keyboard? IE don't allow keyboard dismal except by cancel?

**Comment by kidbombay** [comment]
Though in the contacts iOS app this flow works fine.

**Comment by kidbombay** [comment]
test on latest build

**Comment by qualityanalystweb** [comment]
@kidbombay @mayur43s  Now after pressing cancel it shows Keyboard first and then again pressing cancel all contacts are displayed. So I think no problem any more. One issue I have to press cancel twice after the keyboard is not in place of the screen
