### ISSUE TITLE
Empty event list when cursor is placed in search text field

### ISSUE THREAD

**Issue by qualityanalystweb** [flavorgroup/bouncer#53]
![empty event list](https://cloud.githubusercontent.com/assets/16776424/23319279/83b415ca-fa9b-11e6-888f-8a3788546b05.jpg)
Environment: iOS 102.1
Description:
Initially when cursor is placed on search text field no events are displayed

Steps to reproduce:
1. Launch app in iOS
2. Login to account
3. Tap on the search field under My Events
4. Observe the screen

Expected Result:
Although the user starts typing in when there is no text in Search field then list of all available events to be displayed

**Comment by qualityanalystweb** [comment]
Same issue with ticket holders search feature https://docs.google.com/spreadsheets/d/1OPpNWtAW82gXoxfalYaNUbJtk0UItbermDM-dnMPdkg/edit?ts=58a35186#gid=343331866&range=B5

**Comment by kidbombay** [comment]
No this is correct as is. When you haven't typed anything into google, no results are shown.

**Comment by qualityanalystweb** [comment]
Google does not know whats in our mind. But this scenario is totally different since we have exhaustive list of available ticket holders for event
