### ISSUE TITLE
Two loading spinner appears under Event screen

### ISSUE THREAD

**Issue by qualityanalystweb** [flavorgroup/bouncer#54]
Environment: iOS 102.1
Description:
Two loading spinner appears under Event screen

Steps to reproduce:
1. Launch app in iOS
2. Login to account
3. Tap and drag the screen down
4. Observe the screen

Expected Result:
Only one loading spinner should appear
![two spinners](https://cloud.githubusercontent.com/assets/16776424/23321379/e02db640-faa4-11e6-92d5-4fe9f6a09bd7.jpg)

**Comment by kidbombay** [comment]
test on latest build

**Comment by qualityanalystweb** [comment]
Fix is OK and QA'd.
