### ISSUE TITLE
Add Guest List Contact Detail View

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#55]
https://www.dropbox.com/s/9oyvds19py2revh/guestlist_contact_detail_03.png?dl=0

- [x] Tapping on ticket cell anywhere in app shows this (ticket list, ticket search)
- [x] @kidbombay to update get guest list contact API
- [x] Title is "Ticket Holder" if has ticket
- [x] Title is "Guest" if no ticket
- [x] Check In button at top right if not checked in
- [x] Check Out button at the top right if checked in
- [x] Show username if tied to user and link to upallnight.us/username
- [x] Don't show ticket section if no ticket
- [x] Always show checked in section. Leave values blank if no data.
- [x] Show user.name in gold color if user.is_subscriber
- [x] Show ticket.name color in gold on ticket.is_gold

**Comment by kidbombay** [comment]
http://upallnight.us/docs/guestlist_contacts/get_guest_list_contact

**Comment by kidbombay** [comment]
@mayur43s I'm changing the API slightly to finish this. Please view updated api.
The old fields are still there so nothing should break for you. But to finish this screen you'll need to use new api structure.

http://upallnight.us/docs/guestlist_contacts/get_guest_list_contact

**Comment by kidbombay** [comment]
Test on version 0.7.0

**Comment by kidbombay** [comment]
@mayur43s forgot to add Show name in gold color if user.is_subscriber

**Comment by mayur43s** [comment]
@kidbombay for now I'm updating this color on basis on value of `ticket_is_gold`

**Comment by kidbombay** [comment]
let me be clear.
user.name color should be based on user.is_subscriber
ticket.name color should be based on ticket.is_gold

**Comment by qualityanalystweb** [comment]
Working as expected  though unable to check guest checkin which is not enabled while booking ticket

**Comment by qualityanalystweb** [comment]
@PremKumta QA verified now its your turn to double check unable to find the label though "QA Verified"

**Comment by kidbombay** [comment]
This isn't ready yet. @mayur43s has to finish the color items first for gold.

**Comment by mayur43s** [comment]
@kidbombay, @qualityanalystweb I've fixed the color items in build 0.7.0 (2).

**Comment by qualityanalystweb** [comment]
@mayur43s @kidbombay These two color options "Show user.name in gold color if user.is_subscriber and  Show ticket.name color in gold on ticket.is_gold" are working as expected
