### ISSUE TITLE
Ticket list not refreshed after scan

### ISSUE THREAD

**Issue by PremKumta** [flavorgroup/bouncer#56]
After check in by scanning a ticket, the ticket list does not update to show that a user is scanned in. Only shows up on refresh

**Comment by PremKumta** [comment]
this is reproducable on any ticket you scan with the app

**Comment by kidbombay** [comment]
@PremKumta Titles should be short and clear.
Steps to repro should always exist. Without good bug reporting, we can't fix issues

Step 1
Go to event x
Purchase a free or paid ticket
open bouncer with event x
scan qr code for ticket
same ticket in ticket list isn't updated to show checked in state

**Comment by kidbombay** [comment]
In order to fix this, we need to add a database on the iOS app. This isn't a small change.
But it's something we'll need to do long term.
I'm leaning towards https://realm.io

@PremKumta does this have to be fixed before 1.0?

**Comment by mayur43s** [comment]
I have done the changes for updating the contact checkin status on successful scan and changes are there in build 0.7.0 (1).

**Comment by kidbombay** [comment]
@prem please test this as well.

**Comment by PremKumta** [comment]
how did we fix this @mayur43s without the database fix?

**Comment by PremKumta** [comment]
I verified this is working but going to leave this open as per @kidbombay he says it should have taken a significant dev effort.

**Comment by mayur43s** [comment]
@PremKumta For now when a user does a scan we are using notifications for lopping through the local set of contacts array to update its status.
