### ISSUE TITLE
Scanned poorly printed ticket with fuzzy QR code and was unable to check in a user. 

### ISSUE THREAD

**Issue by PremKumta** [flavorgroup/bouncer#57]
No way to check the correct ticket in because there’s no number on ticket list / not currently ticket detail page

**Comment by kidbombay** [comment]
Would you just use the name on the ticket then?

**Comment by PremKumta** [comment]
yes you'd use the name but the issues is that the user had 4 tickets. How do you know you are checking in the correct one?

with ticket detail this may be worked out. let's see

**Comment by PremKumta** [comment]
how is this QR ready ?

**Comment by PremKumta** [comment]
tested check in from ticket detail and it passed
