### ISSUE TITLE
Scanning 2 copies of the same ticket created 2 “Already Checked” in messages, on refresh of ticket list the correct ticket was checked in

### ISSUE THREAD

**Issue by PremKumta** [flavorgroup/bouncer#58]
Scanning 2 copies of the same ticket created 2 “Already Checked” in messages, on refresh of ticket list the correct ticket was checked in

**Comment by kidbombay** [comment]
We need A LOT more than detail than this in order to QA.
Exact steps please.

Ketan Anjaria

Developer & Designer <http://kidbombay.com>, Writer
<https://medium.com/@kidbombay>, Photographer
<http://instagram.com/kidbombay>

@kidbombay <http://twitter.com/kidbombay>

415-260-8742

**Comment by PremKumta** [comment]
Checking in Annie Edwards
Order 681612928459 Ticket 637699543546

Rob and Prem simultaneously scanned 2 printed copies of the same ticket
Both Bouncer Apps said Alread Checked In
Returned to ticket list and not updated checked in
Refreshed and now checked in tickets appear in different order in the lists 
- most likely should include ticket number on each ticket on ticket list

**Comment by kidbombay** [comment]
Send the links the order. Again this is very hard to understand.
Step 1  - Opened app on iPhone 6s  one with version x
Step 2  - Opened app on iPhone 6 with version x
Step 3 ?
I can't tell from your instruction the order of things.

**Comment by PremKumta** [comment]
see above

**Comment by robgrega** [comment]
This is really two issues.

Issue 1: Two simultaneous scans of the same ticket on two devices produced simultaneous error (already checked in) messages on both devices, but actual result was that one of the tickets did get checked in.

Issue 2: The list on the two devices shows the same ticket in different order.

**Comment by kidbombay** [comment]
What's the QA status in this?

**Comment by kidbombay** [comment]
@robgrega @PremKumta still waiting for QA status on this. Please don't fall behind in QA.

**Comment by robgrega** [comment]
None of us have really been in the office together to attempt to test this with two devices at the same time.

**Comment by robgrega** [comment]
@PremKumta let's determine a precise time where we can specifically test this issue this week.

**Comment by kidbombay** [comment]
Please test this today.
