### ISSUE TITLE
Add Guest Button to Tickets List

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#63]
https://www.dropbox.com/s/swlh6982vqwnwqt/tickets_06.png?dl=0

- [ ] Add a navigation right bar item to ticket list called Add
- [ ] Links to Add Guest Screen #64

**Comment by mayur43s** [comment]
I've done the changes for this issues and are available in 0.7.3 (2).

**Comment by qualityanalystweb** [comment]
Add guest option appears

**Comment by kidbombay** [comment]
@mayur43s this button should be blue.

**Comment by mayur43s** [comment]
I've done the changes for updating the Add button color to blue and those changes are available in 0.7.4 (1).
