### ISSUE TITLE
Implement Add Guest Screen

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#64]
https://www.dropbox.com/s/ta5ryca84n4bgr9/add_guest_01.png?dl=0

- [x] Comes up from bottom as modal
- [x] Can be launched from various screens (Tickets List, other screens)
- [x] Close button Dismisses
- [x] Multiline input field with placeholder
- [x] Done button at the top right. Enabled when input is valid (more than 0 characters)
- [x] Ability to choose from available guest lists (@kidbombay yo create api)
- [x] Call guestlist/add api when done clicked and close screen.
- [x] Refresh guest list contacts api when screen is closed after done

**Comment by kidbombay** [comment]
http://upallnight.us/docs/guestlists/get_all_guest_lists_for_an_event is api call for add guest list screen
Call with ticketed: false

**Comment by kidbombay** [comment]
http://upallnight.us/docs/guestlists/update_guest_list is API call to add guests

**Comment by qualityanalystweb** [comment]
@mayur43s 1. Unable to Checkin guest user at tickets page
2. "Refresh guest list contacts api when screen is closed after done" after this step ticket scrolling is not smooth
![unable to checkin guest user at ticket page](https://cloud.githubusercontent.com/assets/16776424/23763664/2e16d1dc-04c0-11e7-9a3d-5de025c260f0.jpg)

**Comment by kidbombay** [comment]
@qualityanalystweb don't remove the priority tags ever.

**Comment by qualityanalystweb** [comment]
Affirmative!

**Comment by mayur43s** [comment]
I've done the changes for solving checkin issue. I've also done the changes for scrolling the list to the top and refresh it when user adds a guest. All the changes are available in 0.7.4 (1).

**Comment by kidbombay** [comment]
After I add a guest on the guest list tab the lists needs to refresh to show new count.

**Comment by kidbombay** [comment]
Backend fixed for refresh.
