### ISSUE TITLE
Implement Dashboard Tab

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#69]
https://www.dropbox.com/s/93ety3ytn60xtwe/dashboard_02.png?dl=0

- [ ] tab is only accessible if user has correct role (same as seeing sales on my events)
- [x] use new event_invoice api to get data (@kidbombay to implement)
- [ ] Do not add add ticket or edit button yet

**Comment by kidbombay** [comment]
http://upallnight.us/docs/event_invoices/get_invoice_for_event

**Comment by mayur43s** [comment]
I've done the changes for implementing dashboard tab and those changes are available in 0.7.6 (1).

**Comment by qualityanalystweb** [comment]
QAd, Able to see dashboard if user have permission above Guestlist

**Comment by kidbombay** [comment]
Works perfectly.
