### ISSUE TITLE
Add support for iPad

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#74]
Only need to support portrait orientation.
What's the estimate in hours?

**Comment by kidbombay** [comment]
@Shrejas this will be your first task. What's your estimate?

**Comment by Shrejas** [comment]
@kidbombay only iPad support will take 4-5 hours, it'll just adjust constraints for bigger screens, if we need to adopt exact UI (including fonts and iPad specific sizes for UI elements) then it'll take time    2-3 days.

**Comment by Shrejas** [comment]
Done the changes for updating layout of header view on dashboard screen and scan overlay on scan screen dynamically to support iPad with latest build 0.8.2 (2).

**Comment by kidbombay** [comment]
@shinyobjects please test on iPad.


Ketan Anjaria

Developer & Designer <http://kidbombay.com>, Writer
<https://medium.com/@kidbombay>, Photographer
<http://instagram.com/kidbombay>

@kidbombay <http://twitter.com/kidbombay>

415-260-8742
