### ISSUE TITLE
Add sign up link on Login Screen

### ISSUE THREAD

**Issue by PremKumta** [flavorgroup/bouncer#80]
Add sign up link:
That opens mobile browser linking here - https://upallnight.us/sign_up in safari (not in app)

https://www.dropbox.com/s/baiw74sit1gyp0k/login_error_06.png?dl=0

**Comment by kidbombay** [comment]
@Shrejas new issue for you.

**Comment by Shrejas** [comment]
Changes are done with 0.8.2 (2)

**Comment by qualityanalystweb** [comment]
Tapping on "Need Account?" link redirects to signup page through browser
