### ISSUE TITLE
Add background and launch images iPad size

### ISSUE THREAD

**Issue by Shrejas** [flavorgroup/bouncer#81]
- [x] Login Background image 
- [x] Launch image 

**Required sizes:**

1x: 768x1024  
2x: 1536x2048

**Comment by robgrega** [comment]
Login images:

https://www.dropbox.com/s/5b5h81djrh1hfsg/loading_ipad.png?dl=0
https://www.dropbox.com/s/ae0ygwbe9s8yxnf/loading_ipad%402x.png?dl=0

Launch images:

https://www.dropbox.com/s/ez3v2ptmvxv7rlu/login_ipad.png?dl=0
https://www.dropbox.com/s/94nhk27zy81p3oh/login_ipad%402x.png?dl=0

**Comment by Shrejas** [comment]
Changes are updated for adding required images for iPad support with build 0.8.2 (2).

**Comment by kidbombay** [comment]
@robgrega please test on iPad.

**Comment by kidbombay** [comment]
@shinyobjects

**Comment by robgrega** [comment]
Tested this on a regular iPad. 
I see both the launch and login images.
Thanks
