### ISSUE TITLE
Add launch image for iPhone

### ISSUE THREAD

**Issue by robgrega** [flavorgroup/bouncer#82]
it doesn't seem that we've set the launch screen images for iPhone
When I open the app I see a white screen

Please let me know if these sizes are incorrect

https://www.dropbox.com/s/u5m6e5bio8u9x0l/loading%402x.png?dl=0
https://www.dropbox.com/s/2vakqxsee1ao2x0/loading%403x.png?dl=0

cc @kidbombay

**Comment by kidbombay** [comment]
We need all sizes now
iPhone 5, iPhone 6, iPhone 6+, iPad

**Comment by kidbombay** [comment]
Isn't this a duplicate of #81?
