### ISSUE TITLE
Bar Button Item Text should have kerning

### ISSUE THREAD

**Issue by kidbombay** [flavorgroup/bouncer#87]
The add ![](http://i.imgur.com/ho2tWo7.jpg) button here doesn't have a kerning of 1. All bar button text should have kerning.

**Comment by kidbombay** [comment]
Status?

**Comment by mayur43s** [comment]
Changes are done and available in 0.8.5 (3).

**Comment by kidbombay** [comment]
Mayur for design issues, add a screenshot next time.
